/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Gains } from './Gains';
export type { GymJunkie } from './GymJunkie';

export { Gains__factory } from './factories/Gains__factory';
export { GymJunkie__factory } from './factories/GymJunkie__factory';
